# Absenteeism Integration

Now that we have the preprocessing steps and the built model and scaler, we can integrate all of them into one file.

Here, I will run the preprocessing and model testing on a new unseen absenteeism dataset, which we can later deploy if we want.

## Import the Module and Libraries

In [7]:
import pandas as pd

from absenteeism_module import *

## Load the Data

In [8]:
pd.read_csv('../Dataset/Absenteeism_new_data.csv')

,ID,Reason for Absence,Date,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets
0,22,27,01/06/2018,179,26,30,237.656,19,3,0,0
1,10,7,04/06/2018,361,52,28,237.656,27,1,1,4
2,14,23,06/06/2018,155,12,34,237.656,25,1,2,0
3,17,25,08/06/2018,179,22,40,237.656,22,2,2,0
4,14,10,08/06/2018,155,12,34,237.656,25,1,2,0
5,28,11,11/06/2018,225,26,28,237.656,24,1,1,2
6,16,7,13/06/2018,118,15,46,275.089,25,1,2,0
7,22,27,13/06/2018,179,26,30,275.089,19,3,0,0
8,34,26,15/06/2018,118,10,37,275.089,28,1,0,0
9,34,10,20/06/2018,118,10,37,275.089,28,1,0,0
10,23,22,21/06/2018,378,49,36,275.089,21,1,2,4
11,36,19,21/06/2018,118,13,50,275.089,31,1,1,0
12,12,19,22/06/2018,233,51,31,275.089,21,2,1,8
13,22,27,22/06/2018,179,26,30,275.089,19,3,0,0
14,2,0,25/06/2018,235,29,48,275.089,33,1,1,5
15,21,0,28/06/2018,268,11,33,275.089,25,2,0,0
16,36,19,28/06/2018,118,13,50,275.089,31,1,1,0
17,22,13,28/06/2018,179,26,30,275.089,19,3,0,0
18,15,28,28/06/2018,291,31,40,275.089,25,1,1,1
19,22,13,02/07/2018,179,26,30,275.089,19,3,0,0
20,34,25,02/07/2018,118,10,37,275.089,28,1,0,0
21,12,22,05/07/2018,233,51,31,275.089,21,2,1,8
22,34,8,06/07/2018,118,10,37,275.089,28,1,0,0
23,34,10,11/07/2018,118,10,37,275.089,28,1,0,0
24,12,22,11/07/2018,233,51,31,275.089,21,2,1,8
25,5,26,11/07/2018,235,20,43,264.604,38,1,1,0
26,12,19,13/07/2018,233,51,31,264.604,21,2,1,8
27,9,6,16/07/2018,228,14,58,264.604,22,1,2,1
28,34,28,16/07/2018,118,10,37,264.604,28,1,0,0
29,9,6,17/07/2018,228,14,58,264.604,22,1,2,1
30,6,22,17/07/2018,189,29,33,264.604,25,1,2,2
31,34,23,18/07/2018,118,10,37,264.604,28,1,0,0
32,10,22,18/07/2018,361,52,28,264.604,27,1,1,4
33,28,22,18/07/2018,225,26,28,264.604,24,1,1,2
34,13,13,23/07/2018,369,17,31,264.604,25,1,3,0
35,11,14,24/07/2018,289,36,33,264.604,30,1,2,1
36,1,11,24/07/2018,235,11,37,264.604,29,3,1,1
37,4,0,24/07/2018,118,14,40,271.219,34,1,1,8
38,8,0,25/07/2018,231,35,39,271.219,35,1,2,2
39,35,0,27/07/2018,179,45,53,271.219,25,1,1,1

## Create an Absenteeism Model

In [9]:
# create an instance of the model
# pass the model and scaler created previously
model = absenteeism_model('model', 'scaler')

C:\Users\Shiva\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.1.3 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\Shiva\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.1.3 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [10]:
# load and clean the data
model.load_and_clean_data('../Dataset/Absenteeism_new_data.csv')

In [11]:
# check the scaled data
model.data

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Day of the Week,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,False,0.0,False,True,-0.102784,1.344231,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
1,True,0.0,False,False,-0.102784,-1.359682,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
2,False,0.0,False,True,-0.102784,-0.007725,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
3,False,0.0,False,True,-0.102784,1.344231,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690
4,True,0.0,False,False,-0.102784,1.344231,-1.016322,-0.379188,-0.408580,0,0.880469,-0.589690
5,True,0.0,False,False,-0.102784,-1.359682,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
6,True,0.0,False,False,-0.102784,-0.007725,-1.574681,1.503305,-0.408580,0,0.880469,-0.589690
7,False,0.0,False,True,-0.102784,-0.007725,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
8,False,0.0,False,True,-0.102784,1.344231,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
9,True,0.0,False,False,-0.102784,-0.007725,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
10,False,0.0,False,True,-0.102784,0.668253,2.348925,-0.065439,-1.349389,0,0.880469,2.843016
11,False,0.0,True,False,-0.102784,0.668253,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
12,False,0.0,True,False,-0.102784,1.344231,0.160760,-0.849811,-1.349389,1,-0.019280,6.275721
13,False,0.0,False,True,-0.102784,1.344231,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
14,False,0.0,False,False,-0.102784,-1.359682,0.190942,1.817054,1.473038,0,-0.019280,3.701192
15,False,0.0,False,False,-0.102784,0.668253,0.688938,-0.536062,-0.408580,1,-0.919030,-0.589690
16,False,0.0,True,False,-0.102784,0.668253,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690
17,True,0.0,False,False,-0.102784,0.668253,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
18,False,0.0,False,True,-0.102784,0.668253,1.036026,0.562059,-0.408580,0,-0.019280,0.268487
19,True,0.0,False,False,0.182726,-1.359682,-0.654143,-1.006686,-1.819793,1,-0.919030,-0.589690
20,False,0.0,False,True,0.182726,-1.359682,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
21,False,0.0,False,True,0.182726,0.668253,0.160760,-0.849811,-1.349389,1,-0.019280,6.275721
22,True,0.0,False,False,0.182726,1.344231,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
23,True,0.0,False,False,0.182726,-0.007725,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
24,False,0.0,False,True,0.182726,-0.007725,0.160760,-0.849811,-1.349389,1,-0.019280,6.275721
25,False,0.0,False,True,0.182726,-0.007725,0.190942,1.032682,2.649049,0,-0.019280,-0.589690
26,False,0.0,True,False,0.182726,1.344231,0.160760,-0.849811,-1.349389,1,-0.019280,6.275721
27,True,0.0,False,False,0.182726,-1.359682,0.085306,3.385799,-1.114186,0,0.880469,0.268487
28,False,0.0,False,True,0.182726,-1.359682,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
29,True,0.0,False,False,0.182726,-0.683704,0.085306,3.385799,-1.114186,0,0.880469,0.268487
30,False,0.0,False,True,0.182726,-0.683704,-0.503235,-0.536062,-0.408580,0,0.880469,1.126663
31,False,0.0,False,True,0.182726,-0.007725,-1.574681,0.091435,0.297027,0,-0.919030,-0.589690
32,False,0.0,False,True,0.182726,-0.007725,2.092381,-1.320435,0.061825,0,-0.019280,2.843016
33,False,0.0,False,True,0.182726,-0.007725,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663
34,True,0.0,False,False,0.182726,-1.359682,2.213108,-0.849811,-0.408580,0,1.780219,-0.589690
35,True,0.0,False,False,0.182726,-0.683704,1.005844,-0.536062,0.767431,0,0.880469,0.268487
36,True,0.0,False,False,0.182726,-0.683704,0.190942,0.091435,0.532229,1,-0.019280,0.268487
37,False,0.0,False,False,0.182726,-0.683704,-1.574681,0.562059,1.708240,0,-0.019280,6.275721
38,False,0.0,False,False,0.182726,-0.007725,0.130578,0.405184,1.943442,0,0.880469,1.126663
39,False,0.0,False,False,0.182726,1.344231,-0.654143,2.601427,-0.408580,0,-0.019280,0.268487

## Predict the Outputs

1: Excessive Absenteeism
0: Moderate Absenteeism

In [12]:
model.predicted_outputs()

,Reason 1,Reason 2,Reason 3,Reason 4,Month Value,Day of the Week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Probability,Prediction
0,False,0.0,False,True,6,4,179,26,30,237.656,19,1,0,0,0.122031,0
1,True,0.0,False,False,6,0,361,52,28,237.656,27,0,1,4,0.920170,1
2,False,0.0,False,True,6,2,155,12,34,237.656,25,0,2,0,0.275680,0
3,False,0.0,False,True,6,4,179,22,40,237.656,22,1,2,0,0.212287,0
4,True,0.0,False,False,6,4,155,12,34,237.656,25,0,2,0,0.652933,1
5,True,0.0,False,False,6,0,225,26,28,237.656,24,0,1,2,0.803103,1
6,True,0.0,False,False,6,2,118,15,46,275.089,25,0,2,0,0.582053,1
7,False,0.0,False,True,6,2,179,26,30,275.089,19,1,0,0,0.170836,0
8,False,0.0,False,True,6,4,118,10,37,275.089,28,0,0,0,0.083704,0
9,True,0.0,False,False,6,2,118,10,37,275.089,28,0,0,0,0.498037,0
10,False,0.0,False,True,6,3,378,49,36,275.089,21,0,2,4,0.454964,0
11,False,0.0,True,False,6,3,118,13,50,275.089,31,0,1,0,0.499568,0
12,False,0.0,True,False,6,4,233,51,31,275.089,21,1,1,8,0.373998,0
13,False,0.0,False,True,6,4,179,26,30,275.089,19,1,0,0,0.122031,0
14,False,0.0,False,False,6,0,235,29,48,275.089,33,0,1,5,0.116734,0
15,False,0.0,False,False,6,3,268,11,33,275.089,25,1,0,0,0.169223,0
16,False,0.0,True,False,6,3,118,13,50,275.089,31,0,1,0,0.499568,0
17,True,0.0,False,False,6,3,179,26,30,275.089,19,1,0,0,0.553557,1
18,False,0.0,False,True,6,3,291,31,40,275.089,25,0,1,1,0.336602,0
19,True,0.0,False,False,7,0,179,26,30,275.089,19,1,0,0,0.695247,1
20,False,0.0,False,True,7,0,118,10,37,275.089,28,0,0,0,0.169873,0
21,False,0.0,False,True,7,3,233,51,31,275.089,21,1,1,8,0.090175,0
22,True,0.0,False,False,7,4,118,10,37,275.089,28,0,0,0,0.405595,0
23,True,0.0,False,False,7,2,118,10,37,275.089,28,0,0,0,0.502855,1
24,False,0.0,False,True,7,2,233,51,31,275.089,21,1,1,8,0.107677,0
25,False,0.0,False,True,7,2,235,20,43,264.604,38,0,1,0,0.472893,0
26,False,0.0,True,False,7,4,233,51,31,264.604,21,1,1,8,0.378521,0
27,True,0.0,False,False,7,0,228,14,58,264.604,22,0,2,1,0.736414,1
28,False,0.0,False,True,7,0,118,10,37,264.604,28,0,0,0,0.169873,0
29,True,0.0,False,False,7,1,228,14,58,264.604,22,0,2,1,0.696482,1
30,False,0.0,False,True,7,1,189,29,33,264.604,25,0,2,2,0.311950,0
31,False,0.0,False,True,7,2,118,10,37,264.604,28,0,0,0,0.121302,0
32,False,0.0,False,True,7,2,361,52,28,264.604,27,0,1,4,0.519671,1
33,False,0.0,False,True,7,2,225,26,28,264.604,24,0,1,2,0.276853,0
34,True,0.0,False,False,7,0,369,17,31,264.604,25,0,3,0,0.979699,1
35,True,0.0,False,False,7,1,289,36,33,264.604,30,0,2,1,0.930886,1
36,True,0.0,False,False,7,1,235,11,37,264.604,29,1,1,1,0.848241,1
37,False,0.0,False,False,7,1,118,14,40,271.219,34,0,1,8,0.027963,0
38,False,0.0,False,False,7,2,231,35,39,271.219,35,0,2,2,0.252319,0
39,False,0.0,False,False,7,4,179,45,53,271.219,25,0,1,1,0.040740,0

As seen above, the model is predicting whether is person is likely to be excessively absent from work given the input values. Hence, our model is working as expected.

## Export the Predicted Outputs

In [13]:
model.predicted_outputs().to_csv('../Dataset/Absenteeism_predictions_new_data.csv', index=False)